image: Visual Studio 2017

platform:
  - Any CPU

matrix:
  fast_finish: true

before_build:
  - cmd: git submodule update --init --recursive
  - ps: New-Item -ItemType Directory -Force -Path build
  - ps: cd build
  - ps: cmake ..

build:
  parallel: true
  project: build/orbum.sln