language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cmake
            - libboost-all-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

install: true

before_script:
  - eval "${MATRIX_EVAL}"
  - echo "CC test... `${CC} --verison`"
  - echo "CXX test... `${CXX} --verison`"
  - mkdir -p build
  - cd build

script:
  - cmake ..
  - cmake --build .
